export const Images = {
  // --- src/assets/images ---
  appName: require("../assets/images/appName.png"),
  avatar1: require("../assets/images/avatar_1.png"),
  avatar2: require("../assets/images/avatar_2.png"),
  avatar3: require("../assets/images/avatar_3.png"),
  avatar4: require("../assets/images/avatar_4.png"),
  avatar5: require("../assets/images/avatar_5.png"),
  back: require("../assets/images/back.png"),
  check: require("../assets/images/check.png"),
  eyeOff: require("../assets/images/eye-off.png"),
  eyeOn: require("../assets/images/eye-on.png"),
  female: require("../assets/images/female.png"),
  formychild: require("../assets/images/formychild.png"),
  formyself: require("../assets/images/formyself.png"),
  male: require("../assets/images/male.png"),
  onboard1: require("../assets/images/onboard1.png"),
  onboard2: require("../assets/images/onboard2.png"),
  onboard3: require("../assets/images/onboard3.png"),
  // Onboarding: screen GIFs per step
  onboardingScreen1: require("../assets/gif/screen1.gif"),
  onboardingScreen2: require("../assets/gif/screen2.gif"),
  onboardingScreen3: require("../assets/gif/screen3.gif"),
  registered: require("../assets/images/registered.png"),
  uncheck: require("../assets/images/uncheck.png"),

  // Bottom tab bar icons
  icHome: require("../assets/images/ic_home.png"),
  icLeaderboard: require("../assets/images/ic_leaderboard.png"),
  icRoutine: require("../assets/images/ic_routine.png"),
  icBadges: require("../assets/images/ic_badges.png"),
  placeholder: require("../assets/images/placeholder.png"),
  homeSelected: require("../assets/images/homeSelected.png"),
  leaderboardSelected: require("../assets/images/leaderboardSelected.png"),
  routineSelected: require("../assets/images/routineSelected.png"),
  badgeSelected: require("../assets/images/badgeSelected.png"),

  // --- assets/images (legacy folder; keep for existing design assets) ---
  accountSetting: require("../assets/images/accountSetting.png"),
  appLogo: require("../assets/images/appLogo.png"),
  appSettings: require("../assets/images/appSettings.png"),
  calender: require("../assets/images/calender.png"),
  changeActivity: require("../assets/images/changeActivity.png"),
  changeEthnicity: require("../assets/images/changeEthnicity.png"),
  changeHeight: require("../assets/images/changeHeight.png"),
  changeName: require("../assets/images/changeName.png"),
  changeNutrition: require("../assets/images/changeNutrition.png"),
  changeParentHeight: require("../assets/images/changeParentHeight.png"),
  changePassword: require("../assets/images/changePassword.png"),
  changeSleep: require("../assets/images/changeSleep.png"),
  changeSupplements: require("../assets/images/changeSupplements.png"),
  changeWeight: require("../assets/images/changeWeight.png"),
  deleteAccount: require("../assets/images/deleteAccount.png"),
  height: require("../assets/images/height.png"),
  helpCenter: require("../assets/images/helpCenter.png"),
  logout: require("../assets/images/logout.png"),
  manageNotifications: require("../assets/images/manageNotifications.png"),
  manageSubscription: require("../assets/images/manageSubscription.png"),
  notification: require("../assets/images/notification.png"),
  notificationBell: require("../assets/images/notificationBell.png"),

  // Metric cards (Current Height, Current Weight, Edit)
  currentHeight: require("../assets/images/currentHeight.png"),
  currentWeight: require("../assets/images/currentWeight.png"),
  edit: require("../assets/images/edit.png"),
  growth: require("../assets/images/growth.png"),
  streak: require("../assets/images/streak.png"),
  premium: require("../assets/images/premium.png"),
  freeUser: require("../assets/images/freeUser.png"),
  premiumUser: require("../assets/images/premiumUser.png"),
  subscriber: require("../assets/images/subscriber.png"),
  freePlan: require("../assets/images/freePlan.png"),
  freeCheck: require("../assets/images/freeCheck.png"),
  paidPlan: require("../assets/images/paidPlan.png"),
  paidCheck: require("../assets/images/paidCheck.png"),
  privacyPolicy: require("../assets/images/privacyPolicy.png"),
  reportIssue: require("../assets/images/reportIssue.png"),
  termsCondition: require("../assets/images/termsCondition.png"),
  // topicdetail images are screen-specific; add here if they exist later.

  selectedCheck: require("../assets/images/selected_Check_Icon.png"),
  badgeUnlock: require("../assets/images/badgeUnlock.png"),
  badgeLock: require("../assets/images/badgeLock.png"),
  lock: require("../assets/images/lock.png"),
  lock_1: require("../assets/images/lock_1.png"),
  lock_2: require("../assets/images/lock_2.png"),
  lock_3: require("../assets/images/lock_3.png"),
  badgesMainIcon: require("../assets/images/Badges_Main_Icon.png"),
  bagesLockedIcon: require("../assets/images/badges_Lock_Icon.png"),
  noWifi: require("../assets/images/noWifi.png"),

  // Leaderboard
  leaderboardHeader: require("../assets/images/leaderboardheader.png"),
  crown: require("../assets/images/crown.png"),
} as const;
