require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '16.0'

prepare_react_native_project!

target 'TruHeight' do
  use_expo_modules!
  # Keep modular headers limited to Firebase utility pods required by Swift pods.
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  # Some third-party pods (e.g. react-native-iap on New Architecture) depend on
  # React Native's third-party pods, but CocoaPods may not auto-resolve them when
  # using prebuilt RN artifacts. Pin to the local podspec so it can be found.
  if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
    rn_third_party_podspecs = File.join(config[:reactNativePath], 'third-party-podspecs')
    pod 'boost', :podspec => File.join(rn_third_party_podspecs, 'boost.podspec')
    pod 'DoubleConversion', :podspec => File.join(rn_third_party_podspecs, 'DoubleConversion.podspec')
    pod 'fast_float', :podspec => File.join(rn_third_party_podspecs, 'fast_float.podspec')
    pod 'fmt', :podspec => File.join(rn_third_party_podspecs, 'fmt.podspec')
    pod 'glog', :podspec => File.join(rn_third_party_podspecs, 'glog.podspec')
    pod 'RCT-Folly/Fabric', :podspec => File.join(rn_third_party_podspecs, 'RCT-Folly.podspec')
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Ensure RCT-Folly can resolve <folly/*.h> includes while compiling.
    installer.pods_project.targets.each do |target|
      next unless target.name == 'RCT-Folly'

      target.build_configurations.each do |build_config|
        header_search_paths = build_config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
        header_search_paths = header_search_paths.is_a?(Array) ? header_search_paths.join(' ') : header_search_paths.to_s

        folly_root = '$(PODS_ROOT)/RCT-Folly'
        unless header_search_paths.include?(folly_root)
          build_config.build_settings['HEADER_SEARCH_PATHS'] = "#{header_search_paths} #{folly_root}"
        end
      end
    end

    # Work around intermittent Swift frontend crashes in NitroIap generated files
    # by compiling the pod in whole-module mode.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        next unless target.name == 'NitroIap'

        # Work around Swift frontend crashes in Nitro-generated Swift by
        # reducing frontend parallelism and disabling reflection metadata.
        build_config.build_settings['SWIFT_COMPILATION_MODE'] = 'singlefile'
        build_config.build_settings['SWIFT_NUM_THREADS'] = '1'
        existing_flags = build_config.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
        unless existing_flags.include?('-disable-reflection-metadata')
          build_config.build_settings['OTHER_SWIFT_FLAGS'] = "#{existing_flags} -Xfrontend -disable-reflection-metadata"
        end
      end
    end
  end
end
